# Use an existing node alpine image as a base image.
FROM node:20-alpine

#Set working directory
WORKDIR /app

#Copy the package.json and package.lock.json file 
COPY  package*.json ./

#Install application dependencies 
RUN npm install

# Copy the rest of the application files.

COPY . .

#Expose the port 
EXPOSE 3000

#Run the application
CMD [ "npm", "start" ]