#Reference compose file version 3
version: '3'
services:
#service name is React_crud
react-app:
#build from docker file
build:
# expose 3000 as hosting port & 3000 in container port
ports:
- "3000:3000"
environment:
#Provide your license key for activation as environment variable to docker container
- REACT_APP_SERVER_URL=http://server:5000